In [10]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [11]:

print(type(list_))  
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [12]:
for i in list_:
    print(type(i))

for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


3. Considering the following changes in the variable, array_list:

In [13]:
array_list = np.array(object = list_, dtype = int)

for i in list_:
    print(type(i))

for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

4. Write a code to find the following characteristics of variable, num_array:

In [18]:
#(i) shape
print(num_array.shape)

#(ii) size
print(num_array.size)

(2, 3)
6


5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [21]:
ar1 = np.zeros((3,3))
print(ar1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


6.Create an identity matrix of shape (5,5) using numpy functions?

In [22]:
ar2 = np.eye((5,5))

TypeError: 'tuple' object cannot be interpreted as an integer